# Generated by Django 4.0.2 on 2022-02-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='repositoryUrl',
            new_name='repository_url',
        ),
    ]
